language: node_js
node_js:
- node

before_deploy:
- npm run build

deploy:
  skip_cleanup: true
  provider: pages
  github-token:
    secure: "BqA2sER0s4nV3NEk9bYD1OpSx0AqozS7zMwNBaWVc9tF6HqjcNCU0llIGmCVXcSN9yjKkiz9+2dADOsuCmMm/OOc54rjxf2pbUE1es9PodI+DgZjzi1eyriphMi8vNTdxjtP/ZueC63hpI/bmTGN9M7mb5f39hHahpls7TE5Q8uHNurOZWQw86qiYozmF6jlr4EVpijfBhkkhP7chnloSlkIUssZ8t1mEpM2xcKBav5OOi3wl+e8aHCYrH+PlBXdb3keS7gq/QkovE0AlMr21Dq115wEqX4PGLIuHDsaO9gFWugDpjveRsBtHZjxKAK/rxIdMvfFZ8A+56dfPdMZJenscWjBEqr9XF3WHFYFE05HgqkedlfJ3ZbUivVf8ZEXUPO1UUZwqodmr+k/luINAdF92m3PuN7ox/I/brJ6bKZWl3kK/bnaqXrBOEEfbjQdmig+Yzvqp4HunFvKExekY07q9vaoY84yoJUkdedjmIWLgPxW5OLdbEmryfxxTXWmbLZ3hvlDM1jQ/UjH07lnzMPofIBNqrkqaJ2kQKUNYsHI3P8xtOg76HOBppBtx8rYmlB9HXc+ymH8gE4ijJs8zQFtYwRh9O3rEgwkeHrx4MZ/MlbFGTxEe1IUGAzzNd1kAcBSzMuKzwb+eNbYv/lUhYPZXMCJQa/P1xdCat/dYN8="
  local-dir: build/public
